### ISSUE TITLE
internal error

### ISSUE THREAD

**Issue by Andrey77711** [woblavobla/redmine_custom_reminder#1]
Hello. After installing plugin and migrating i got an internal error:

Internal error

An error occurred on the page you were trying to access.
 If you continue to experience problems please contact your Redmine administrator for assistance.

If you are the Redmine administrator, check your log files for details about the error.

Back

An internal error after i go to administration-Пользовательские email-уведомления

is there any opportunity to fix it?

**Comment by Andrey77711** [comment]
bundle exec rake redmine:plugins:migrate NAME=redmine_custom_reminder RAILS_ENV=production --trace
(in /var/www/redmine)
** Invoke redmine:plugins:migrate (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute redmine:plugins:migrate
Migrating redmine_custom_reminder (Redmine Custom Email Reminder)...
-- [](5.2)
-- [](5.2)
rake aborted!
NoMethodError: undefined method `[]' for #<ActiveRecord::Migration:0x0000000174c768>
/var/lib/gems/2.3.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:664:in `block in method_missing'
/var/lib/gems/2.3.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:634:in `block in say_with_time'
/usr/lib/ruby/2.3.0/benchmark.rb:293:in `measure'
/var/lib/gems/2.3.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:634:in `say_with_time'
/var/lib/gems/2.3.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:654:in `method_missing'
/var/lib/gems/2.3.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:416:in `method_missing'
/var/www/redmine/plugins/redmine_custom_reminder/db/migrate/001_initialize_custom_reminders.rb:1:in `<top (required)>'
/var/lib/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
/var/lib/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `block in require'
/var/lib/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:240:in `load_dependency'
/var/lib/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
/var/lib/gems/2.3.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:777:in `load_migration'
/var/lib/gems/2.3.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:773:in `migration'
/var/lib/gems/2.3.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:768:in `disable_ddl_transaction'
/var/lib/gems/2.3.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:1051:in `use_transaction?'
/var/lib/gems/2.3.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:961:in `rescue in block in migrate'
/var/lib/gems/2.3.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:958:in `block in migrate'
/var/lib/gems/2.3.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:955:in `each'
/var/lib/gems/2.3.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:955:in `migrate'
/var/lib/gems/2.3.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:823:in `up'
/var/lib/gems/2.3.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:801:in `migrate'
/var/www/redmine/lib/redmine/plugin.rb:481:in `migrate_plugin'
/var/www/redmine/lib/redmine/plugin.rb:453:in `migrate'
/var/www/redmine/lib/redmine/plugin.rb:464:in `migrate'
/var/www/redmine/lib/tasks/redmine.rake:135:in `block (3 levels) in <top (required)>'
/var/lib/gems/2.3.0/gems/rake-12.3.1/lib/rake/task.rb:271:in `block in execute'
/var/lib/gems/2.3.0/gems/rake-12.3.1/lib/rake/task.rb:271:in `each'
/var/lib/gems/2.3.0/gems/rake-12.3.1/lib/rake/task.rb:271:in `execute'
/var/lib/gems/2.3.0/gems/rake-12.3.1/lib/rake/task.rb:213:in `block in invoke_with_call_chain'
/usr/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/var/lib/gems/2.3.0/gems/rake-12.3.1/lib/rake/task.rb:193:in `invoke_with_call_chain'
/var/lib/gems/2.3.0/gems/rake-12.3.1/lib/rake/task.rb:182:in `invoke'
/var/lib/gems/2.3.0/gems/rake-12.3.1/lib/rake/application.rb:160:in `invoke_task'
/var/lib/gems/2.3.0/gems/rake-12.3.1/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/var/lib/gems/2.3.0/gems/rake-12.3.1/lib/rake/application.rb:116:in `each'
/var/lib/gems/2.3.0/gems/rake-12.3.1/lib/rake/application.rb:116:in `block in top_level'
/var/lib/gems/2.3.0/gems/rake-12.3.1/lib/rake/application.rb:125:in `run_with_threads'
/var/lib/gems/2.3.0/gems/rake-12.3.1/lib/rake/application.rb:110:in `top_level'
/var/lib/gems/2.3.0/gems/rake-12.3.1/lib/rake/application.rb:83:in `block in run'
/var/lib/gems/2.3.0/gems/rake-12.3.1/lib/rake/application.rb:186:in `standard_exception_handling'
/var/lib/gems/2.3.0/gems/rake-12.3.1/lib/rake/application.rb:80:in `run'
/var/lib/gems/2.3.0/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
/usr/local/bin/rake:23:in `load'
/usr/local/bin/rake:23:in `<main>'

Caused by:
NoMethodError: undefined method `[]' for #<ActiveRecord::Migration:0x0000000174c768>
/var/lib/gems/2.3.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:664:in `block in method_missing'
/var/lib/gems/2.3.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:634:in `block in say_with_time'
/usr/lib/ruby/2.3.0/benchmark.rb:293:in `measure'
/var/lib/gems/2.3.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:634:in `say_with_time'
/var/lib/gems/2.3.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:654:in `method_missing'
/var/lib/gems/2.3.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:416:in `method_missing'
/var/www/redmine/plugins/redmine_custom_reminder/db/migrate/001_initialize_custom_reminders.rb:1:in `<top (required)>'
/var/lib/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
/var/lib/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `block in require'
/var/lib/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:240:in `load_dependency'
/var/lib/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
/var/lib/gems/2.3.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:777:in `load_migration'
/var/lib/gems/2.3.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:773:in `migration'
/var/lib/gems/2.3.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:768:in `disable_ddl_transaction'
/var/lib/gems/2.3.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:1051:in `use_transaction?'
/var/lib/gems/2.3.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:1043:in `ddl_transaction'
/var/lib/gems/2.3.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:997:in `execute_migration_in_transaction'
/var/lib/gems/2.3.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:959:in `block in migrate'
/var/lib/gems/2.3.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:955:in `each'
/var/lib/gems/2.3.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:955:in `migrate'
/var/lib/gems/2.3.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:823:in `up'
/var/lib/gems/2.3.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:801:in `migrate'
/var/www/redmine/lib/redmine/plugin.rb:481:in `migrate_plugin'
/var/www/redmine/lib/redmine/plugin.rb:453:in `migrate'
/var/www/redmine/lib/redmine/plugin.rb:464:in `migrate'
/var/www/redmine/lib/tasks/redmine.rake:135:in `block (3 levels) in <top (required)>'
/var/lib/gems/2.3.0/gems/rake-12.3.1/lib/rake/task.rb:271:in `block in execute'
/var/lib/gems/2.3.0/gems/rake-12.3.1/lib/rake/task.rb:271:in `each'
/var/lib/gems/2.3.0/gems/rake-12.3.1/lib/rake/task.rb:271:in `execute'
/var/lib/gems/2.3.0/gems/rake-12.3.1/lib/rake/task.rb:213:in `block in invoke_with_call_chain'
/usr/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/var/lib/gems/2.3.0/gems/rake-12.3.1/lib/rake/task.rb:193:in `invoke_with_call_chain'
/var/lib/gems/2.3.0/gems/rake-12.3.1/lib/rake/task.rb:182:in `invoke'
/var/lib/gems/2.3.0/gems/rake-12.3.1/lib/rake/application.rb:160:in `invoke_task'
/var/lib/gems/2.3.0/gems/rake-12.3.1/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/var/lib/gems/2.3.0/gems/rake-12.3.1/lib/rake/application.rb:116:in `each'
/var/lib/gems/2.3.0/gems/rake-12.3.1/lib/rake/application.rb:116:in `block in top_level'
/var/lib/gems/2.3.0/gems/rake-12.3.1/lib/rake/application.rb:125:in `run_with_threads'
/var/lib/gems/2.3.0/gems/rake-12.3.1/lib/rake/application.rb:110:in `top_level'
/var/lib/gems/2.3.0/gems/rake-12.3.1/lib/rake/application.rb:83:in `block in run'
/var/lib/gems/2.3.0/gems/rake-12.3.1/lib/rake/application.rb:186:in `standard_exception_handling'
/var/lib/gems/2.3.0/gems/rake-12.3.1/lib/rake/application.rb:80:in `run'
/var/lib/gems/2.3.0/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
/usr/local/bin/rake:23:in `load'
/usr/local/bin/rake:23:in `<main>'
Tasks: TOP => redmine:plugins:migrate

**Comment by woblavobla** [comment]
I will fix it; This issue is because migration was written for rails 5;
