### ISSUE TITLE
запуск планировщика рассылки

### ISSUE THREAD

**Issue by Andrey77711** [woblavobla/redmine_custom_reminder#3]
при запуске планировщика рассылки (Запустить планировщик email-рассылки ) в плагине возникает ошибка: 

Internal error
An error occurred on the page you were trying to access.
If you continue to experience problems please contact your Redmine administrator for assistance.

If you are the Redmine administrator, check your log files for details about the error.

Back

redmine/custom_reminders/schedule_custom_reminder?force=true

**Comment by woblavobla** [comment]
А в log/production.log что по поводу ошибки?

**Comment by Andrey77711** [comment]
прикладываю лог. обновил версию плагина. (ту что сегодня выложили на сайт)
ошибка та же самая.
[production.log](https://github.com/woblavobla/redmine_custom_reminder/files/2710240/production.log)

**Comment by woblavobla** [comment]
@Andrey77711 

> NameError (uninitialized constant CustomRemindersController::CustomRemindersEmailNotificationJob
> Did you mean?  CustomFieldEnumerationsController)

Добавил в инструкцию пункт.

2) Create application_job.rb in app/jobs/application_job.rb with following content

class ApplicationJob < ActiveJob::Base
  # Automatically retry jobs that encountered a deadlock
  # retry_on ActiveRecord::Deadlocked

  # Most jobs are safe to ignore if the underlying records are no longer available
  # discard_on ActiveJob::DeserializationError
end

**Comment by Andrey77711** [comment]
подойдет только для linux?

**Comment by woblavobla** [comment]
@Andrey77711 На Windows gem whenever не будет работать, так как он использует cron.

**Comment by Andrey77711** [comment]
а для redmine 3.4 не поправляли? будет всё работать?

**Comment by woblavobla** [comment]
@Andrey77711 Должно работать, но опять же тестирую для master ветки. Основное требование наличие application_job.rb

**Comment by Andrey77711** [comment]
ладно. дома развернут ubuntu, проверю. на боевой машине не могу тестить.. Если что-то доработаете, напишите тогда?

**Comment by woblavobla** [comment]
@Andrey77711 Следите за изменениями. Но поддержка Windows не планируется. На боевом трекере работает на CentOs 7 в docker.

**Comment by Andrey77711** [comment]
хорошо. у нас на ubuntu 16.04

**Comment by Andrey77711** [comment]
на чем разрабатываете?

**Comment by woblavobla** [comment]
@Andrey77711 RubyMine.

**Comment by Andrey77711** [comment]
как к примеру доработать один/два плагина, которые работают на rails 4.2 но не работают на rails 5.2 и редмайне 4.0?

**Comment by Andrey77711** [comment]
спасибо. буду следить за обновлениями.

**Comment by Andrey77711** [comment]
еще вопрос - не настраивали параметр обработки входящей почты с exchange?
