### ISSUE TITLE
"redmine_custom_reminder" usage

### ISSUE THREAD

**Issue by sosogh** [woblavobla/redmine_custom_reminder#4]
Hi

Thank you for your great work on "redmine_custom_reminder"

We are looking for a way to send email notification when it meets all the following conditions  :
1. the issue is older than 1 day
2. Priority is Immediate or Urgent
3. Status is new or In Progress 

It seems "redmine_custom_reminder" can do it .
But I am new to ruby  ,  I do not understand the step:

2. Create application_job.rb in app/jobs/application_job.rb with following content
3. bundle install
4. rake redmine:plugins # Migrating db
5. bundle exec whenever -i redmine_custom_reminder -f plugins/redmine_custom_reminder/config/schedule.rb 

Colud you please give more example ?
Thank you !

**Comment by woblavobla** [comment]
@sosogh Readme is updated, i hope that now it is more understandable now.

> We are looking for a way to send email notification when it meets all the following conditions :
> 
>1. the issue is older than 1 day
>2. Priority is Immediate or Urgent
>3. Status is new or In Progress

All this can be made in this plugin. You only have to write some code that checks this conditions.
